### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by jeroenrinzema** [auxten/postgresql-parser#3]
👋🏻 , I am interested in contributing but was wondering if you would be able to add a license to the project?

**Comment by auxten** [comment]
Sure, license inherited from CockroachDB added

**Comment by jeroenrinzema** [comment]
Thanks!

**Comment by saolof** [comment]
@auxten  This may or may not be worth reopening since cockroachdb seems to have released their parser code under an apache license?
https://github.com/cockroachdb/cockroachdb-parser/commits/main/

Of course, rebasing the project on top of that and ensuring that any cockroachdb code used is apache licensed may be a lot of work, depending on when it was fetched, though if it was fetched three years ago it may already have converted to apache.
